import { getProjectSpec } from "../db/repositories/projects.js";
import { generateSpecCss } from "../motion/generator/css.js";
import type { MotionComponent, MotionSpec } from "@openmotion/shared";

export interface CodeExport {
  code: string;
  language: "css" | "json" | "tsx";
  filename: string;
}

/** Export the full stylesheet for a project. */
export function exportProjectCss(projectId: string): CodeExport | null {
  const spec = getProjectSpec(projectId);
  if (!spec) return null;
  const css = generateSpecCss(spec.components);
  const header = `/* OpenMotion — ${spec.project.name} */\n/* ${spec.components.length} component(s), exported as CSS @keyframes + rules */\n\n`;
  return {
    code: header + css,
    language: "css",
    filename: `${slug(spec.project.name)}.css`,
  };
}

/** Export the MotionSpec as pretty-printed JSON. */
export function exportProjectJson(projectId: string): CodeExport | null {
  const spec = getProjectSpec(projectId);
  if (!spec) return null;
  const json = JSON.stringify(spec, null, 2);
  return {
    code: json,
    language: "json",
    filename: `${slug(spec.project.name)}.json`,
  };
}

/** Generate a self-contained React component from the spec. */
export function exportProjectReact(projectId: string): CodeExport | null {
  const spec = getProjectSpec(projectId);
  if (!spec) return null;
  const componentName = toPascalCase(spec.project.name) || "OpenMotion";
  const css = generateSpecCss(spec.components);
  const elements = spec.components
    .sort((a, b) => a.orderIndex - b.orderIndex)
    .map((c) => renderReactElement(c))
    .join("\n      ");

  const code = `import { useEffect, useRef } from "react";
import "./${slug(spec.project.name)}.css";

/**
 * ${componentName} — generated by OpenMotion.
 * ${spec.components.length} animated layer(s).
 */
export function ${componentName}() {
  const ref = useRef<HTMLDivElement>(null);

  // Shift+R replays all animations.
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (!e.shiftKey || e.key.toLowerCase() !== "r") return;
      ref.current?.querySelectorAll<HTMLElement>("[data-om-name]").forEach((el) => {
        el.style.animation = "none";
        void el.offsetWidth;
        el.style.animation = "";
      });
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, []);

  return (
    <div ref={ref} className="om-root">
      ${elements}
    </div>
  );
}
`;

  const cssBlock = `\n/* --- ${slug(spec.project.name)}.css --- */\n${css}\n`;
  return {
    code: code + cssBlock,
    language: "tsx",
    filename: `${componentName}.tsx`,
  };
}

function renderReactElement(c: MotionComponent): string {
  const tag = String(c.style?._tag ?? "div");
  const content = String(c.style?._content ?? c.name);
  const className = c.selector ? undefined : `om-c-${c.id}`;
  const cls = className ? ` className="${className}"` : "";
  return `<${tag}${cls} data-om-name="${escapeAttr(c.name)}">${escapeText(content)}</${tag}>`;
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "openmotion";
}

function toPascalCase(s: string): string {
  return s
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

function escapeAttr(s: string): string {
  return s.replace(/"/g, "&quot;");
}

function escapeText(s: string): string {
  return s.replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
