import { easingPreset } from "@openmotion/shared";
import { draft, kf, type TemplateDef } from "./helper.js";

export const chromaticPulseTemplate: TemplateDef = {
  id: "tpl-chromatic-pulse",
  name: "Chromatic Pulse",
  category: "emphasis",
  description: "RGB channel split pulse synchronized like a heartbeat — red, green, and blue channels separate and converge rhythmically for a digital vital-signs effect.",
  tags: ["chromatic", "pulse", "rgb", "heartbeat", "split", "digital", "vital"],
  build: () => [
    draft("Pulse Container", {
      durationMs: 2000,
      easing: easingPreset("linear"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [],
      style: {
        _content: "",
        _tag: "div",
        width: "200px",
        height: "200px",
        borderRadius: "16px",
        backgroundColor: "#0a0a0a",
        overflow: "hidden",
        position: "relative",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
      },
    }),
    draft("Chromatic Core", {
      durationMs: 1600,
      easing: easingPreset("ease-out"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { scale: 0.85, opacity: 0.4 }),
        kf(0.15, { scale: 1.15, opacity: 1 }),
        kf(0.3, { scale: 0.95, opacity: 0.7 }),
        kf(0.45, { scale: 1.05, opacity: 0.9 }),
        kf(0.7, { scale: 0.9, opacity: 0.5 }),
        kf(1, { scale: 0.85, opacity: 0.4 }),
      ],
      style: {
        _content: "PULSE",
        _tag: "div",
        width: "80px",
        height: "80px",
        borderRadius: "50%",
        backgroundColor: "#ffffff",
        color: "#0a0a0a",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: "10px",
        fontWeight: "700",
        letterSpacing: "1px",
        position: "absolute",
      },
    }),
    draft("RGB Split Red", {
      durationMs: 1600,
      easing: easingPreset("ease-out"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { translateX: 0, opacity: 0 }),
        kf(0.15, { translateX: -6, opacity: 0.6 }),
        kf(0.3, { translateX: -2, opacity: 0.3 }),
        kf(0.45, { translateX: -4, opacity: 0.4 }),
        kf(1, { translateX: 0, opacity: 0 }),
      ],
      style: {
        _content: "PULSE",
        _tag: "div",
        width: "80px",
        height: "80px",
        borderRadius: "50%",
        backgroundColor: "transparent",
        color: "rgba(255,40,40,0.8)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: "10px",
        fontWeight: "700",
        letterSpacing: "1px",
        position: "absolute",
        mixBlendMode: "screen",
      },
    }),
    draft("RGB Split Blue", {
      durationMs: 1600,
      easing: easingPreset("ease-out"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { translateX: 0, opacity: 0 }),
        kf(0.15, { translateX: 6, opacity: 0.6 }),
        kf(0.3, { translateX: 2, opacity: 0.3 }),
        kf(0.45, { translateX: 4, opacity: 0.4 }),
        kf(1, { translateX: 0, opacity: 0 }),
      ],
      style: {
        _content: "PULSE",
        _tag: "div",
        width: "80px",
        height: "80px",
        borderRadius: "50%",
        backgroundColor: "transparent",
        color: "rgba(40,80,255,0.8)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: "10px",
        fontWeight: "700",
        letterSpacing: "1px",
        position: "absolute",
        mixBlendMode: "screen",
      },
    }),
  ],
};
