import { easingPreset } from "@openmotion/shared";
import { draft, kf, type TemplateDef } from "./helper.js";

// Crystalline shatter: geometric shards scatter outward in a crystalline pattern
export const crystallineShatterTemplate: TemplateDef = {
  id: "tpl-crystalline-shatter",
  name: "Crystalline Shatter",
  category: "exit",
  description: "Geometric crystal shards scatter outward in a sharp, angular pattern — a dramatic exit that conveys fragmentation and release.",
  tags: ["exit", "crystal", "shatter", "shard", "geometric", "angular", "dramatic", "fragment"],
  build: () => [
    draft("Crystal Shard TL", {
      durationMs: 800,
      delayMs: 0,
      easing: easingPreset("ease-in-cubic"),
      iterationCount: 1,
      keyframes: [
        kf(0, { opacity: 1, translateX: 0, translateY: 0, rotate: 0, scale: 1 }),
        kf(1, { opacity: 0, translateX: -120, translateY: -80, rotate: -45, scale: 0.3 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "40px",
        height: "40px",
        background: "linear-gradient(135deg, #67e8f9 0%, #06b6d4 50%, #0891b2 100%)",
        clipPath: "polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)",
        boxShadow: "0 0 20px rgba(6,182,212,0.6)",
        position: "absolute",
        left: "45%",
        top: "40%",
      },
    }),
    draft("Crystal Shard TR", {
      durationMs: 800,
      delayMs: 50,
      easing: easingPreset("ease-in-cubic"),
      iterationCount: 1,
      keyframes: [
        kf(0, { opacity: 1, translateX: 0, translateY: 0, rotate: 0, scale: 1 }),
        kf(1, { opacity: 0, translateX: 120, translateY: -80, rotate: 45, scale: 0.3 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "35px",
        height: "35px",
        background: "linear-gradient(225deg, #a5f3fc 0%, #22d3ee 50%, #06b6d4 100%)",
        clipPath: "polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%)",
        position: "absolute",
        left: "50%",
        top: "40%",
      },
    }),
    draft("Crystal Shard BL", {
      durationMs: 750,
      delayMs: 80,
      easing: easingPreset("ease-in-cubic"),
      iterationCount: 1,
      keyframes: [
        kf(0, { opacity: 1, translateX: 0, translateY: 0, rotate: 0, scale: 1 }),
        kf(1, { opacity: 0, translateX: -100, translateY: 100, rotate: -30, scale: 0.4 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "45px",
        height: "45px",
        background: "linear-gradient(45deg, #67e8f9 0%, #0e7490 100%)",
        clipPath: "polygon(20% 0%, 80% 0%, 100% 100%, 0% 100%)",
        position: "absolute",
        left: "45%",
        top: "50%",
      },
    }),
    draft("Crystal Shard BR", {
      durationMs: 800,
      delayMs: 60,
      easing: easingPreset("ease-in-cubic"),
      iterationCount: 1,
      keyframes: [
        kf(0, { opacity: 1, translateX: 0, translateY: 0, rotate: 0, scale: 1 }),
        kf(1, { opacity: 0, translateX: 100, translateY: 100, rotate: 30, scale: 0.3 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "38px",
        height: "38px",
        background: "linear-gradient(315deg, #cffafe 0%, #06b6d4 100%)",
        clipPath: "polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)",
        boxShadow: "0 0 15px rgba(34,211,238,0.5)",
        position: "absolute",
        left: "50%",
        top: "50%",
      },
    }),
    draft("Crystal Core Burst", {
      durationMs: 400,
      delayMs: 0,
      easing: easingPreset("ease-out-cubic"),
      iterationCount: 1,
      keyframes: [
        kf(0, { opacity: 1, scale: 1 }),
        kf(0.5, { opacity: 0.8, scale: 1.4 }),
        kf(1, { opacity: 0, scale: 2 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "60px",
        height: "60px",
        background: "radial-gradient(circle, #ffffff 0%, #22d3ee 30%, transparent 70%)",
        borderRadius: "50%",
        position: "absolute",
        left: "47%",
        top: "47%",
      },
    }),
  ],
};
