import { easingPreset } from "@openmotion/shared";
import { draft, kf, type TemplateDef } from "./helper.js";

// Data stream: vertical lines of light cascade downward like a digital rain,
// creating a matrix-like data flow effect. Conveys technology and data motion.
export const dataStreamTemplate: TemplateDef = {
  id: "tpl-data-stream",
  name: "Data Stream",
  category: "load",
  description: "Vertical streams of luminous particles cascade downward in a digital rain — a matrix-like data flow that conveys technology and information motion.",
  tags: ["load", "data", "stream", "digital", "matrix", "rain", "technology", "flow"],
  build: () => [
    draft("Stream Column A", {
      durationMs: 1200,
      delayMs: 0,
      easing: easingPreset("ease-in"),
      iterationCount: "infinite",
      keyframes: [
        kf(0, { opacity: 0, translateY: -200 }),
        kf(0.1, { opacity: 1 }),
        kf(0.9, { opacity: 0.8 }),
        kf(1, { opacity: 0, translateY: 400 }),
      ],
      style: {
        _content: "01001",
        _tag: "div",
        width: "20px",
        height: "120px",
        color: "#00ff9f",
        fontFamily: "monospace",
        fontSize: "14px",
        lineHeight: "1.2",
        textShadow: "0 0 10px #00ff9f",
        position: "absolute",
        left: "50px",
        top: "0",
      },
    }),
    draft("Stream Column B", {
      durationMs: 1000,
      delayMs: 300,
      easing: easingPreset("ease-in"),
      iterationCount: "infinite",
      keyframes: [
        kf(0, { opacity: 0, translateY: -200 }),
        kf(0.1, { opacity: 0.9 }),
        kf(0.9, { opacity: 0.7 }),
        kf(1, { opacity: 0, translateY: 400 }),
      ],
      style: {
        _content: "10110",
        _tag: "div",
        width: "20px",
        height: "100px",
        color: "#00ff9f",
        fontFamily: "monospace",
        fontSize: "12px",
        lineHeight: "1.2",
        textShadow: "0 0 8px #00ff9f",
        position: "absolute",
        left: "120px",
        top: "0",
      },
    }),
    draft("Stream Column C", {
      durationMs: 1400,
      delayMs: 600,
      easing: easingPreset("ease-in"),
      iterationCount: "infinite",
      keyframes: [
        kf(0, { opacity: 0, translateY: -200 }),
        kf(0.1, { opacity: 1 }),
        kf(0.9, { opacity: 0.6 }),
        kf(1, { opacity: 0, translateY: 400 }),
      ],
      style: {
        _content: "11001",
        _tag: "div",
        width: "20px",
        height: "140px",
        color: "#00ff9f",
        fontFamily: "monospace",
        fontSize: "16px",
        lineHeight: "1.2",
        textShadow: "0 0 12px #00ff9f",
        position: "absolute",
        left: "200px",
        top: "0",
      },
    }),
  ],
};
