import { easingPreset } from "@openmotion/shared";
import { draft, kf, type TemplateDef } from "./helper.js";

export const dataStreamTemplate: TemplateDef = {
  id: "tpl-data-stream",
  name: "Data Stream",
  category: "emphasis",
  description: "Matrix-style digital rain with cascading characters fading through the viewport — a cyberpunk data flow effect.",
  tags: ["data", "stream", "matrix", "digital", "rain", "cyberpunk", "code"],
  build: () => [
    draft("Stream Container", {
      durationMs: 3000,
      easing: easingPreset("linear"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [],
      style: {
        _content: "",
        _tag: "div",
        width: "320px",
        height: "240px",
        borderRadius: "8px",
        backgroundColor: "#050505",
        overflow: "hidden",
        position: "relative",
      },
    }),
    draft("Stream Column A", {
      durationMs: 2400,
      delayMs: 0,
      easing: easingPreset("linear"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { translateY: "-100%", opacity: 0 }),
        kf(0.1, { opacity: 1 }),
        kf(0.9, { opacity: 0.8 }),
        kf(1, { translateY: "240%", opacity: 0 }),
      ],
      style: {
        _content: "01001\n10110\n01101\n10010\n11001\n00110",
        _tag: "div",
        fontFamily: "monospace",
        fontSize: "11px",
        lineHeight: "1.4",
        color: "rgba(180,255,180,0.8)",
        textShadow: "0 0 6px rgba(120,255,120,0.5)",
        position: "absolute",
        top: "0",
        left: "20px",
        whiteSpace: "pre",
      },
    }),
    draft("Stream Column B", {
      durationMs: 3000,
      delayMs: 400,
      easing: easingPreset("linear"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { translateY: "-100%", opacity: 0 }),
        kf(0.1, { opacity: 0.9 }),
        kf(0.9, { opacity: 0.6 }),
        kf(1, { translateY: "240%", opacity: 0 }),
      ],
      style: {
        _content: "11010\n00101\n11100\n01011\n10110\n00011",
        _tag: "div",
        fontFamily: "monospace",
        fontSize: "11px",
        lineHeight: "1.4",
        color: "rgba(150,255,150,0.6)",
        textShadow: "0 0 4px rgba(100,255,100,0.4)",
        position: "absolute",
        top: "0",
        left: "80px",
        whiteSpace: "pre",
      },
    }),
    draft("Stream Column C", {
      durationMs: 2000,
      delayMs: 800,
      easing: easingPreset("linear"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { translateY: "-100%", opacity: 0 }),
        kf(0.1, { opacity: 1 }),
        kf(0.9, { opacity: 0.7 }),
        kf(1, { translateY: "240%", opacity: 0 }),
      ],
      style: {
        _content: "00110\n11001\n01100\n10011\n00110\n11000",
        _tag: "div",
        fontFamily: "monospace",
        fontSize: "11px",
        lineHeight: "1.4",
        color: "rgba(200,255,200,0.9)",
        textShadow: "0 0 8px rgba(140,255,140,0.6)",
        position: "absolute",
        top: "0",
        left: "140px",
        whiteSpace: "pre",
      },
    }),
  ],
};
