import { easingPreset } from "@openmotion/shared";
import { draft, kf, type TemplateDef } from "./helper.js";

export const depthCardTemplate: TemplateDef = {
  id: "tpl-depth-card",
  name: "Depth Card",
  category: "transition",
  description: "A parallax depth card with layered planes that separate in 3D on entrance — foreground, midground, and background shift at different rates for a volumetric reveal.",
  tags: ["depth", "parallax", "3d", "card", "volumetric", "layered", "entrance"],
  build: () => [
    draft("Card Frame", {
      durationMs: 1200,
      easing: easingPreset("smooth"),
      iterationCount: 1,
      direction: "normal",
      fillMode: "forwards",
      keyframes: [
        kf(0, { opacity: 0, scale: 0.92, rotate: 4 }),
        kf(1, { opacity: 1, scale: 1, rotate: 0 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "280px",
        height: "180px",
        borderRadius: "12px",
        backgroundColor: "#1a1a1a",
        boxShadow: "0 20px 40px rgba(0,0,0,0.5), 0 0 0 1px rgba(255,255,255,0.05)",
        overflow: "hidden",
        position: "relative",
        perspective: "800px",
      },
    }),
    draft("Foreground Layer", {
      durationMs: 1000,
      delayMs: 200,
      easing: easingPreset("ease-out"),
      iterationCount: 1,
      direction: "normal",
      fillMode: "forwards",
      keyframes: [
        kf(0, { translateX: 0, translateY: 0, opacity: 0, scale: 0.8 }),
        kf(1, { translateX: 0, translateY: 0, opacity: 1, scale: 1 }),
      ],
      style: {
        _content: "DEPTH",
        _tag: "div",
        width: "200px",
        height: "60px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "8px",
        backgroundColor: "#ffffff",
        color: "#0a0a0a",
        fontSize: "20px",
        fontWeight: "bold",
        letterSpacing: "2px",
        position: "absolute",
        top: "60px",
        left: "40px",
        boxShadow: "0 8px 16px rgba(0,0,0,0.4)",
      },
    }),
    draft("Background Layer", {
      durationMs: 1400,
      delayMs: 0,
      easing: easingPreset("ease-out"),
      iterationCount: 1,
      direction: "normal",
      fillMode: "forwards",
      keyframes: [
        kf(0, { opacity: 0, scale: 1.15 }),
        kf(1, { opacity: 0.5, scale: 1 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "320px",
        height: "220px",
        borderRadius: "16px",
        background: "radial-gradient(circle at 50% 50%, #2a2a2a, #0a0a0a)",
        position: "absolute",
        top: "-20px",
        left: "-20px",
      },
    }),
  ],
};
