import { easingPreset } from "@openmotion/shared";
import { draft, kf, type TemplateDef } from "./helper.js";

// Gravitational pull: elements spiral inward toward a gravitational center
export const gravitationalPullTemplate: TemplateDef = {
  id: "tpl-gravitational-pull",
  name: "Gravitational Pull",
  category: "entrance",
  description: "Elements spiral inward toward a gravitational center, accelerating as they approach — a physics-inspired entrance that conveys attraction and convergence.",
  tags: ["entrance", "gravity", "spiral", "pull", "attract", "converge", "physics", "orbit"],
  build: () => [
    draft("Orbit Body Alpha", {
      durationMs: 1500,
      delayMs: 0,
      easing: easingPreset("ease-in-cubic"),
      iterationCount: 1,
      keyframes: [
        kf(0, { translateX: 200, translateY: -200, rotate: 0, scale: 0.5, opacity: 0 }),
        kf(0.3, { opacity: 0.6, scale: 0.7 }),
        kf(0.7, { translateX: 50, translateY: -50, rotate: 270, scale: 0.9, opacity: 0.9 }),
        kf(1, { translateX: 0, translateY: 0, rotate: 360, scale: 1, opacity: 1 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "60px",
        height: "60px",
        background: "radial-gradient(circle, #fbbf24 0%, #f59e0b 50%, #d97706 100%)",
        borderRadius: "50%",
        boxShadow: "0 0 30px rgba(251,191,36,0.6)",
        position: "absolute",
        left: "45%",
        top: "45%",
      },
    }),
    draft("Orbit Body Beta", {
      durationMs: 1200,
      delayMs: 200,
      easing: easingPreset("ease-in-cubic"),
      iterationCount: 1,
      keyframes: [
        kf(0, { translateX: -180, translateY: 180, rotate: 0, scale: 0.4, opacity: 0 }),
        kf(0.3, { opacity: 0.5, scale: 0.6 }),
        kf(0.7, { translateX: -40, translateY: 40, rotate: -270, scale: 0.85, opacity: 0.8 }),
        kf(1, { translateX: 0, translateY: 0, rotate: -360, scale: 1, opacity: 1 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "50px",
        height: "50px",
        background: "radial-gradient(circle, #60a5fa 0%, #3b82f6 50%, #1d4ed8 100%)",
        borderRadius: "50%",
        boxShadow: "0 0 25px rgba(96,165,250,0.5)",
        position: "absolute",
        left: "47%",
        top: "47%",
      },
    }),
    draft("Gravity Center", {
      durationMs: 1000,
      delayMs: 0,
      easing: easingPreset("ease-out"),
      iterationCount: 1,
      keyframes: [
        kf(0, { scale: 0, opacity: 0 }),
        kf(0.5, { scale: 1.5, opacity: 0.5 }),
        kf(1, { scale: 1, opacity: 1 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "100px",
        height: "100px",
        background: "radial-gradient(circle, #ffffff 0%, rgba(255,255,255,0.3) 30%, transparent 70%)",
        borderRadius: "50%",
        position: "absolute",
        left: "43%",
        top: "43%",
      },
    }),
    draft("Gravity Well Ring", {
      durationMs: 2000,
      delayMs: 0,
      easing: easingPreset("ease-in-out"),
      iterationCount: 1,
      keyframes: [
        kf(0, { scale: 3, opacity: 0, rotate: 0 }),
        kf(0.5, { scale: 1.5, opacity: 0.4, rotate: 180 }),
        kf(1, { scale: 0.5, opacity: 0, rotate: 360 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "200px",
        height: "200px",
        border: "2px solid rgba(251,191,36,0.3)",
        borderRadius: "50%",
        position: "absolute",
        left: "35%",
        top: "35%",
      },
    }),
  ],
};
