import { easingPreset, easingSpring } from "@openmotion/shared";
import { draft, kf, type TemplateDef } from "./helper.js";

/**
 * Magnetic Ripple — a central pulse source emits an expanding field that
 * pushes metallic particles outward, then snaps them back via spring physics.
 * Concentric rings expand and fade while particles oscillate around their
 * rest positions, creating a tactile magnetic attraction/repulsion effect.
 */
export const magneticRippleTemplate: TemplateDef = {
  id: "tpl-magnetic-ripple",
  name: "Magnetic Ripple",
  category: "emphasis",
  description: "Magnetic pulse that emanates outward, pushing metallic particles away then snapping them back with spring physics — a tactile attraction/repulsion field effect.",
  tags: ["magnetic", "ripple", "pulse", "field", "particles", "spring", "attract", "repel"],
  build: () => [
    draft("Magnetic Field Base", {
      durationMs: 2400,
      easing: easingPreset("linear"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [],
      style: {
        _content: "",
        _tag: "div",
        width: "260px",
        height: "260px",
        borderRadius: "50%",
        backgroundColor: "#080808",
        overflow: "hidden",
        position: "relative",
      },
    }),
    draft("Pulse Core", {
      durationMs: 2400,
      easing: easingPreset("ease-out"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { scale: 0.4, opacity: 0.9 }),
        kf(0.2, { scale: 1.2, opacity: 0.4 }),
        kf(0.5, { scale: 0.7, opacity: 0.7 }),
        kf(0.75, { scale: 1, opacity: 0.3 }),
        kf(1, { scale: 0.4, opacity: 0.9 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "40px",
        height: "40px",
        borderRadius: "50%",
        background: "radial-gradient(circle, #ffffff 0%, rgba(200,220,255,0.6) 50%, transparent 80%)",
        boxShadow: "0 0 24px rgba(200,220,255,0.8)",
        position: "absolute",
        top: "110px",
        left: "110px",
      },
    }),
    draft("Ring Wave Inner", {
      durationMs: 2400,
      easing: easingPreset("ease-out"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { scale: 0.2, opacity: 0 }),
        kf(0.15, { scale: 0.6, opacity: 0.8 }),
        kf(0.5, { scale: 1.4, opacity: 0.3 }),
        kf(0.85, { scale: 2, opacity: 0.05 }),
        kf(1, { scale: 2.2, opacity: 0 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "80px",
        height: "80px",
        borderRadius: "50%",
        border: "1.5px solid rgba(220,230,255,0.6)",
        position: "absolute",
        top: "90px",
        left: "90px",
      },
    }),
    draft("Ring Wave Outer", {
      durationMs: 2400,
      delayMs: 300,
      easing: easingPreset("ease-out"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { scale: 0.2, opacity: 0 }),
        kf(0.15, { scale: 0.5, opacity: 0.6 }),
        kf(0.5, { scale: 1.2, opacity: 0.2 }),
        kf(0.85, { scale: 1.8, opacity: 0.03 }),
        kf(1, { scale: 2, opacity: 0 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "100px",
        height: "100px",
        borderRadius: "50%",
        border: "1px solid rgba(180,200,255,0.4)",
        position: "absolute",
        top: "80px",
        left: "80px",
      },
    }),
    draft("Particle North", {
      durationMs: 2400,
      easing: easingSpring(180, 14, 1),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { translateY: 0, opacity: 0.9 }),
        kf(0.2, { translateY: -36, opacity: 1 }),
        kf(0.45, { translateY: -8, opacity: 0.7 }),
        kf(0.65, { translateY: -20, opacity: 0.85 }),
        kf(0.85, { translateY: -4, opacity: 0.75 }),
        kf(1, { translateY: 0, opacity: 0.9 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "10px",
        height: "10px",
        borderRadius: "50%",
        backgroundColor: "#e8e8e8",
        boxShadow: "0 0 6px rgba(220,225,235,0.8)",
        position: "absolute",
        top: "118px",
        left: "125px",
      },
    }),
    draft("Particle South", {
      durationMs: 2400,
      delayMs: 60,
      easing: easingSpring(180, 14, 1),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { translateY: 0, opacity: 0.9 }),
        kf(0.2, { translateY: 36, opacity: 1 }),
        kf(0.45, { translateY: 8, opacity: 0.7 }),
        kf(0.65, { translateY: 20, opacity: 0.85 }),
        kf(0.85, { translateY: 4, opacity: 0.75 }),
        kf(1, { translateY: 0, opacity: 0.9 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "10px",
        height: "10px",
        borderRadius: "50%",
        backgroundColor: "#e8e8e8",
        boxShadow: "0 0 6px rgba(220,225,235,0.8)",
        position: "absolute",
        top: "132px",
        left: "125px",
      },
    }),
    draft("Particle East", {
      durationMs: 2400,
      delayMs: 120,
      easing: easingSpring(180, 14, 1),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { translateX: 0, opacity: 0.9 }),
        kf(0.2, { translateX: 36, opacity: 1 }),
        kf(0.45, { translateX: 8, opacity: 0.7 }),
        kf(0.65, { translateX: 20, opacity: 0.85 }),
        kf(0.85, { translateX: 4, opacity: 0.75 }),
        kf(1, { translateX: 0, opacity: 0.9 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "10px",
        height: "10px",
        borderRadius: "50%",
        backgroundColor: "#e8e8e8",
        boxShadow: "0 0 6px rgba(220,225,235,0.8)",
        position: "absolute",
        top: "125px",
        left: "132px",
      },
    }),
    draft("Particle West", {
      durationMs: 2400,
      delayMs: 180,
      easing: easingSpring(180, 14, 1),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { translateX: 0, opacity: 0.9 }),
        kf(0.2, { translateX: -36, opacity: 1 }),
        kf(0.45, { translateX: -8, opacity: 0.7 }),
        kf(0.65, { translateX: -20, opacity: 0.85 }),
        kf(0.85, { translateX: -4, opacity: 0.75 }),
        kf(1, { translateX: 0, opacity: 0.9 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "10px",
        height: "10px",
        borderRadius: "50%",
        backgroundColor: "#e8e8e8",
        boxShadow: "0 0 6px rgba(220,225,235,0.8)",
        position: "absolute",
        top: "125px",
        left: "118px",
      },
    }),
  ],
};
