import { easingPreset } from "@openmotion/shared";
import { draft, kf, type TemplateDef } from "./helper.js";

export const neonFlickerTemplate: TemplateDef = {
  id: "tpl-neon-flicker",
  name: "Neon Flicker",
  category: "emphasis",
  description: "A neon sign warming up — erratic flicker, buzz dim, and steady-state glow. Captures the turn-on sequence of a cold-cathode tube.",
  tags: ["neon", "flicker", "sign", "glow", "turn-on", "erratic", "light"],
  build: () => [
    draft("Neon Sign", {
      durationMs: 2500,
      easing: easingPreset("linear"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { opacity: 0 }),
        kf(0.05, { opacity: 0.8 }),
        kf(0.07, { opacity: 0.1 }),
        kf(0.1, { opacity: 0.9 }),
        kf(0.12, { opacity: 0.2 }),
        kf(0.15, { opacity: 0.7 }),
        kf(0.18, { opacity: 0.3 }),
        kf(0.22, { opacity: 0.95 }),
        kf(0.25, { opacity: 0.4 }),
        kf(0.3, { opacity: 0.85 }),
        kf(0.35, { opacity: 0.6 }),
        kf(0.4, { opacity: 0.9 }),
        kf(0.5, { opacity: 0.7 }),
        kf(0.55, { opacity: 0.95 }),
        kf(0.6, { opacity: 0.8 }),
        kf(0.7, { opacity: 1 }),
        kf(0.85, { opacity: 0.92 }),
        kf(1, { opacity: 1 }),
      ],
      style: {
        _content: "NEON",
        _tag: "div",
        width: "200px",
        height: "80px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "4px",
        backgroundColor: "#0a0a0a",
        color: "#ffffff",
        fontSize: "32px",
        fontFamily: "sans-serif",
        fontWeight: "300",
        letterSpacing: "6px",
        textShadow: "0 0 8px rgba(255,255,255,0.9), 0 0 16px rgba(255,255,255,0.6), 0 0 32px rgba(255,255,255,0.4)",
        boxShadow: "0 0 24px rgba(255,255,255,0.15), inset 0 0 12px rgba(255,255,255,0.05)",
        border: "1px solid rgba(255,255,255,0.15)",
      },
    }),
  ],
};
