import { easingPreset } from "@openmotion/shared";
import { draft, kf, type TemplateDef } from "./helper.js";

/**
 * Neural Pulse — a neural network activation sequence that visualizes signal
 * propagation through interconnected nodes. Nodes light up in sequence along
 * synapse paths, with energy pulses traveling between them. Original
 * composition exploring graph-based motion choreography with staggered
 * node activation and traveling pulse particles.
 */
export const neuralPulseTemplate: TemplateDef = {
  id: "tpl-neural-pulse",
  name: "Neural Pulse",
  category: "emphasis",
  description:
    "Neural network activation with sequential node firing, synapse energy pulses, and wave propagation — visualizes graph traversal as choreographed motion across interconnected nodes.",
  tags: ["neural", "network", "pulse", "synapse", "activation", "graph", "emphasis", "abstract"],
  build: () => [
    draft("Neural Field", {
      durationMs: 5000,
      easing: easingPreset("linear"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { opacity: 0.85 }),
        kf(0.5, { opacity: 1 }),
        kf(1, { opacity: 0.85 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "420px",
        height: "280px",
        backgroundColor: "#08080F",
        borderRadius: "12px",
        overflow: "hidden",
        position: "relative",
      },
    }),
    draft("Node Alpha", {
      durationMs: 1200,
      easing: easingPreset("ease-out"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { opacity: 0.3, scale: 0.8 }),
        kf(0.15, { opacity: 1, scale: 1.3, boxShadow: "0 0 24px #00E5FF, 0 0 48px #00E5FF" }),
        kf(0.4, { opacity: 0.8, scale: 1, boxShadow: "0 0 12px #00E5FF" }),
        kf(1, { opacity: 0.3, scale: 0.8, boxShadow: "none" }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "16px",
        height: "16px",
        backgroundColor: "#00E5FF",
        borderRadius: "50%",
        position: "absolute",
        top: "60px",
        left: "60px",
      },
    }),
    draft("Node Beta", {
      durationMs: 1200,
      delayMs: 300,
      easing: easingPreset("ease-out"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { opacity: 0.3, scale: 0.8 }),
        kf(0.15, { opacity: 1, scale: 1.3, boxShadow: "0 0 24px #00E5FF, 0 0 48px #00E5FF" }),
        kf(0.4, { opacity: 0.8, scale: 1, boxShadow: "0 0 12px #00E5FF" }),
        kf(1, { opacity: 0.3, scale: 0.8, boxShadow: "none" }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "16px",
        height: "16px",
        backgroundColor: "#00E5FF",
        borderRadius: "50%",
        position: "absolute",
        top: "140px",
        left: "160px",
      },
    }),
    draft("Node Gamma", {
      durationMs: 1200,
      delayMs: 600,
      easing: easingPreset("ease-out"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { opacity: 0.3, scale: 0.8 }),
        kf(0.15, { opacity: 1, scale: 1.3, boxShadow: "0 0 24px #00E5FF, 0 0 48px #00E5FF" }),
        kf(0.4, { opacity: 0.8, scale: 1, boxShadow: "0 0 12px #00E5FF" }),
        kf(1, { opacity: 0.3, scale: 0.8, boxShadow: "none" }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "16px",
        height: "16px",
        backgroundColor: "#00E5FF",
        borderRadius: "50%",
        position: "absolute",
        top: "80px",
        left: "280px",
      },
    }),
    draft("Node Delta", {
      durationMs: 1200,
      delayMs: 900,
      easing: easingPreset("ease-out"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { opacity: 0.3, scale: 0.8 }),
        kf(0.15, { opacity: 1, scale: 1.3, boxShadow: "0 0 24px #00E5FF, 0 0 48px #00E5FF" }),
        kf(0.4, { opacity: 0.8, scale: 1, boxShadow: "0 0 12px #00E5FF" }),
        kf(1, { opacity: 0.3, scale: 0.8, boxShadow: "none" }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "16px",
        height: "16px",
        backgroundColor: "#00E5FF",
        borderRadius: "50%",
        position: "absolute",
        top: "180px",
        left: "340px",
      },
    }),
    draft("Pulse Alpha-Beta", {
      durationMs: 800,
      delayMs: 100,
      easing: easingPreset("ease-in-out"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { opacity: 0, translateX: 0, translateY: 0, scale: 0.5 }),
        kf(0.2, { opacity: 1, scale: 1 }),
        kf(0.8, { opacity: 1, scale: 1 }),
        kf(1, { opacity: 0, translateX: 100, translateY: 80, scale: 0.5 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "8px",
        height: "8px",
        backgroundColor: "#FFFFFF",
        borderRadius: "50%",
        boxShadow: "0 0 12px #FFFFFF, 0 0 24px #00E5FF",
        position: "absolute",
        top: "64px",
        left: "64px",
      },
    }),
    draft("Pulse Beta-Gamma", {
      durationMs: 800,
      delayMs: 400,
      easing: easingPreset("ease-in-out"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { opacity: 0, translateX: 0, translateY: 0, scale: 0.5 }),
        kf(0.2, { opacity: 1, scale: 1 }),
        kf(0.8, { opacity: 1, scale: 1 }),
        kf(1, { opacity: 0, translateX: 120, translateY: -60, scale: 0.5 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "8px",
        height: "8px",
        backgroundColor: "#FFFFFF",
        borderRadius: "50%",
        boxShadow: "0 0 12px #FFFFFF, 0 0 24px #00E5FF",
        position: "absolute",
        top: "144px",
        left: "164px",
      },
    }),
    draft("Pulse Gamma-Delta", {
      durationMs: 800,
      delayMs: 700,
      easing: easingPreset("ease-in-out"),
      iterationCount: "infinite",
      direction: "normal",
      keyframes: [
        kf(0, { opacity: 0, translateX: 0, translateY: 0, scale: 0.5 }),
        kf(0.2, { opacity: 1, scale: 1 }),
        kf(0.8, { opacity: 1, scale: 1 }),
        kf(1, { opacity: 0, translateX: 60, translateY: 100, scale: 0.5 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "8px",
        height: "8px",
        backgroundColor: "#FFFFFF",
        borderRadius: "50%",
        boxShadow: "0 0 12px #FFFFFF, 0 0 24px #00E5FF",
        position: "absolute",
        top: "84px",
        left: "284px",
      },
    }),
  ],
};
