import { easingPreset } from "@openmotion/shared";
import { draft, kf, type TemplateDef } from "./helper.js";

export const prismaticTemplate: TemplateDef = {
  id: "tpl-prismatic",
  name: "Prismatic",
  category: "emphasis",
  description: "Light spectrum split through a prism — RGB channels separate and reconverge in a rhythmic optical dispersion.",
  tags: ["prismatic", "spectrum", "rgb", "split", "chromatic", "optical", "loop"],
  build: () => [
    draft("Prism Core", {
      durationMs: 3000,
      easing: easingPreset("smooth"),
      iterationCount: "infinite",
      direction: "alternate",
      keyframes: [
        kf(0, { scale: 1, opacity: 0.9 }),
        kf(0.5, { scale: 1.08, opacity: 1 }),
        kf(1, { scale: 1, opacity: 0.9 }),
      ],
      style: {
        _content: "PRISM",
        _tag: "div",
        width: "160px",
        height: "160px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "8px",
        backgroundColor: "#0a0a0a",
        color: "#ffffff",
        fontSize: "20px",
        fontFamily: "monospace",
        fontWeight: "bold",
        letterSpacing: "4px",
        boxShadow: "0 0 40px rgba(255,255,255,0.08)",
      },
    }),
    draft("Red Channel", {
      durationMs: 3000,
      easing: easingPreset("ease-in-out"),
      iterationCount: "infinite",
      direction: "alternate",
      keyframes: [
        kf(0, { translateX: 0, opacity: 0 }),
        kf(0.5, { translateX: -12, opacity: 0.5 }),
        kf(1, { translateX: 0, opacity: 0 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "160px",
        height: "160px",
        borderRadius: "8px",
        backgroundColor: "rgba(255,40,40,0.15)",
        position: "absolute",
        top: "0",
        left: "0",
        mixBlendMode: "screen",
      },
    }),
    draft("Blue Channel", {
      durationMs: 3000,
      delayMs: 100,
      easing: easingPreset("ease-in-out"),
      iterationCount: "infinite",
      direction: "alternate",
      keyframes: [
        kf(0, { translateX: 0, opacity: 0 }),
        kf(0.5, { translateX: 12, opacity: 0.5 }),
        kf(1, { translateX: 0, opacity: 0 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "160px",
        height: "160px",
        borderRadius: "8px",
        backgroundColor: "rgba(40,120,255,0.15)",
        position: "absolute",
        top: "0",
        left: "0",
        mixBlendMode: "screen",
      },
    }),
  ],
};
