import { easingPreset } from "@openmotion/shared";
import { draft, kf, type TemplateDef } from "./helper.js";

// Quantum flux: the element phases between probability states — translucent,
// multiplied, jittering — before collapsing into a single solid reality.
export const quantumFluxTemplate: TemplateDef = {
  id: "tpl-quantum-flux",
  name: "Quantum Flux",
  category: "transition",
  description: "The element phases between probability states — translucent, duplicated, micro-jittering — before collapsing into a single solid reality. A quantum indeterminacy transition.",
  tags: ["transition", "quantum", "flux", "probability", "collapse", "superposition", "phase"],
  build: () => [
    draft("Flux Body", {
      durationMs: 1200,
      easing: easingPreset("ease-in-out-cubic"),
      iterationCount: 1,
      keyframes: [
        kf(0, { opacity: 0.3, scale: 1, translateX: 0, blur: 6 }),
        kf(0.2, { opacity: 0.5, scale: 1.04, translateX: -4, blur: 4 }),
        kf(0.4, { opacity: 0.4, scale: 0.97, translateX: 5, blur: 5 }),
        kf(0.6, { opacity: 0.55, scale: 1.03, translateX: -3, blur: 3 }),
        kf(0.8, { opacity: 0.85, scale: 1.01, translateX: 1, blur: 1 }),
        kf(1, { opacity: 1, scale: 1, translateX: 0, blur: 0 }),
      ],
      style: {
        _content: "ψ",
        _tag: "div",
        width: "140px",
        height: "140px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "16px",
        background: "linear-gradient(135deg, #312E81 0%, #6366F1 50%, #06B6D4 100%)",
        color: "rgba(255,255,255,0.95)",
        fontSize: "64px",
        fontWeight: 300,
        boxShadow: "0 8px 32px rgba(99,102,241,0.5)",
      },
    }),
    draft("Echo State A", {
      durationMs: 1200,
      easing: easingPreset("ease-in-out-cubic"),
      iterationCount: 1,
      keyframes: [
        kf(0, { opacity: 0.4, scale: 1, translateX: -12 }),
        kf(0.5, { opacity: 0.25, scale: 1.02, translateX: 8 }),
        kf(1, { opacity: 0, scale: 1, translateX: 0 }),
      ],
      style: {
        _content: "ψ",
        _tag: "div",
        width: "140px",
        height: "140px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "16px",
        background: "linear-gradient(135deg, rgba(49,46,129,0.4) 0%, rgba(99,102,241,0.4) 50%, rgba(6,182,212,0.4) 100%)",
        color: "rgba(165,180,252,0.6)",
        fontSize: "64px",
        fontWeight: 300,
        position: "absolute",
        top: "0",
        left: "0",
      },
    }),
    draft("Echo State B", {
      durationMs: 1200,
      easing: easingPreset("ease-in-out-cubic"),
      iterationCount: 1,
      keyframes: [
        kf(0, { opacity: 0.35, scale: 1, translateX: 14 }),
        kf(0.5, { opacity: 0.2, scale: 0.98, translateX: -10 }),
        kf(1, { opacity: 0, scale: 1, translateX: 0 }),
      ],
      style: {
        _content: "ψ",
        _tag: "div",
        width: "140px",
        height: "140px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "16px",
        background: "linear-gradient(135deg, rgba(49,46,129,0.4) 0%, rgba(99,102,241,0.4) 50%, rgba(6,182,212,0.4) 100%)",
        color: "rgba(103,232,249,0.6)",
        fontSize: "64px",
        fontWeight: 300,
        position: "absolute",
        top: "0",
        left: "0",
      },
    }),
  ],
};
