import { easingPreset } from "@openmotion/shared";
import { draft, kf, type TemplateDef } from "./helper.js";

// Quantum wave: probability density wave function with collapse visualization
export const quantumWaveTemplate: TemplateDef = {
  id: "tpl-quantum-wave",
  name: "Quantum Wave",
  category: "entrance",
  description: "A probability density wave that collapses into form — a quantum-inspired entrance that visualizes the transition from potential to actual.",
  tags: ["entrance", "quantum", "wave", "probability", "collapse", "particle", "physics", "scientific"],
  build: () => [
    // Wave function oscillating
    draft("Quantum Wave A", {
      durationMs: 1800,
      delayMs: 0,
      easing: easingPreset("linear"),
      iterationCount: "infinite",
      keyframes: [
        kf(0, { translateX: -100, opacity: 0 }),
        kf(0.1, { opacity: 1 }),
        kf(0.5, { translateX: 100, opacity: 0.7 }),
        kf(0.9, { opacity: 1 }),
        kf(1, { translateX: -100, opacity: 0 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "6px",
        height: "200px",
        background: "linear-gradient(180deg, transparent 0%, rgba(59,130,246,0.8) 30%, rgba(99,102,241,1) 50%, rgba(59,130,246,0.8) 70%, transparent 100%)",
        borderRadius: "3px",
        position: "absolute",
        left: "30%",
        top: "50%",
        filter: "blur(2px)",
      },
    }),
    draft("Quantum Wave B", {
      durationMs: 1800,
      delayMs: 200,
      easing: easingPreset("linear"),
      iterationCount: "infinite",
      keyframes: [
        kf(0, { translateX: -80, opacity: 0 }),
        kf(0.1, { opacity: 0.8 }),
        kf(0.5, { translateX: 80, opacity: 0.5 }),
        kf(0.9, { opacity: 0.8 }),
        kf(1, { translateX: -80, opacity: 0 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "4px",
        height: "160px",
        background: "linear-gradient(180deg, transparent 0%, rgba(139,92,246,0.8) 30%, rgba(168,85,247,1) 50%, rgba(139,92,246,0.8) 70%, transparent 100%)",
        borderRadius: "2px",
        position: "absolute",
        left: "50%",
        top: "50%",
        filter: "blur(2px)",
      },
    }),
    draft("Quantum Wave C", {
      durationMs: 1800,
      delayMs: 400,
      easing: easingPreset("linear"),
      iterationCount: "infinite",
      keyframes: [
        kf(0, { translateX: -120, opacity: 0 }),
        kf(0.1, { opacity: 0.6 }),
        kf(0.5, { translateX: 120, opacity: 0.4 }),
        kf(0.9, { opacity: 0.6 }),
        kf(1, { translateX: -120, opacity: 0 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "8px",
        height: "180px",
        background: "linear-gradient(180deg, transparent 0%, rgba(34,211,238,0.8) 30%, rgba(6,182,212,1) 50%, rgba(34,211,238,0.8) 70%, transparent 100%)",
        borderRadius: "4px",
        position: "absolute",
        left: "70%",
        top: "50%",
        filter: "blur(2px)",
      },
    }),
    // Particle collapse
    draft("Quantum Particle", {
      durationMs: 600,
      delayMs: 1200,
      easing: easingPreset("ease-out-cubic"),
      iterationCount: 1,
      keyframes: [
        kf(0, { scale: 0.2, opacity: 0 }),
        kf(0.6, { scale: 1.3, opacity: 1 }),
        kf(1, { scale: 1, opacity: 1 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "60px",
        height: "60px",
        background: "radial-gradient(circle, #ffffff 0%, #818cf8 30%, #6366f1 60%, transparent 80%)",
        borderRadius: "50%",
        boxShadow: "0 0 30px rgba(99,102,241,0.9), 0 0 60px rgba(139,92,246,0.5)",
        position: "absolute",
        left: "50%",
        top: "50%",
        transform: "translate(-50%, -50%)",
      },
    }),
  ],
};