import { easingPreset } from "@openmotion/shared";
import { draft, kf, type TemplateDef } from "./helper.js";

// Sonic boom: a concentrated point explodes outward in a shockwave ring,
// leaving the focal element revealed in the wake. Conveys impact and release.
export const sonicBoomTemplate: TemplateDef = {
  id: "tpl-sonic-boom",
  name: "Sonic Boom",
  category: "emphasis",
  description: "A concentrated point detonates into an expanding shockwave ring, revealing the focal element in its wake — a percussive, high-impact emphasis moment.",
  tags: ["emphasis", "sonic", "boom", "shockwave", "impact", "explosion", "percussive"],
  build: () => [
    draft("Focal Element", {
      durationMs: 1100,
      easing: easingPreset("back"),
      iterationCount: 1,
      keyframes: [
        kf(0, { opacity: 0, scale: 0.2 }),
        kf(0.3, { opacity: 0, scale: 0.2 }),
        kf(0.45, { opacity: 1, scale: 1.15 }),
        kf(0.7, { opacity: 1, scale: 0.96 }),
        kf(1, { opacity: 1, scale: 1 }),
      ],
      style: {
        _content: "BOOM",
        _tag: "div",
        width: "180px",
        height: "80px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "10px",
        background: "linear-gradient(135deg, #F97316 0%, #EF4444 100%)",
        color: "#fff",
        fontWeight: 800,
        fontSize: "28px",
        letterSpacing: "2px",
        boxShadow: "0 12px 40px rgba(239,68,68,0.45)",
      },
    }),
    draft("Shockwave Ring", {
      durationMs: 1100,
      easing: easingPreset("ease-out-cubic"),
      iterationCount: 1,
      keyframes: [
        kf(0, { opacity: 0, scale: 0.1 }),
        kf(0.28, { opacity: 0, scale: 0.1 }),
        kf(0.35, { opacity: 1, scale: 0.4 }),
        kf(0.6, { opacity: 0.6, scale: 1.6 }),
        kf(1, { opacity: 0, scale: 3 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "120px",
        height: "120px",
        borderRadius: "50%",
        border: "4px solid rgba(249,115,22,0.9)",
        position: "absolute",
        top: "-20px",
        left: "30px",
        boxShadow: "0 0 30px rgba(249,115,22,0.6)",
      },
    }),
    draft("Inner Flash", {
      durationMs: 1100,
      easing: easingPreset("ease-out-cubic"),
      iterationCount: 1,
      keyframes: [
        kf(0, { opacity: 0, scale: 0 }),
        kf(0.28, { opacity: 0, scale: 0 }),
        kf(0.34, { opacity: 1, scale: 1.8 }),
        kf(0.5, { opacity: 0.5, scale: 1 }),
        kf(0.7, { opacity: 0, scale: 0.8 }),
      ],
      style: {
        _content: "",
        _tag: "div",
        width: "100px",
        height: "100px",
        borderRadius: "50%",
        background: "radial-gradient(circle, rgba(255,255,255,1) 0%, rgba(254,215,170,0.7) 40%, transparent 75%)",
        position: "absolute",
        top: "10px",
        left: "40px",
      },
    }),
  ],
};
